### ISSUE TITLE
Using a trained network to obtain segmentation

### ISSUE THREAD

**Issue by visionresearcher** [198808xc/OrganSegC2F#3]
Hi,

Thanks for your wonderful work. Can you please share the network you have trained on the 82 pancreas images along with the steps to test them on a new image? That will be very useful. 

Thanks

**Comment by 198808xc** [comment]
Hello, sorry for this late reply. I will be uploading the models tomorrow. Thanks for your attention!

**Comment by 198808xc** [comment]
Hello visionresearcher,

All the files are uploaded! Please check README.md (Sec 5) for details.

Note that we did not train the model on all 82 cases because of cross validation. A possible solution is to fuse the results of 4 trained models on your new testing data. It is a bit slower though. Of course, if you want, you can run our codes and train your own models by yourself.

Have fun!
Lingxi
